### ISSUE TITLE
Proposal peer review - From Robo Cops

### ISSUE THREAD

**Issue by ArunKoundinya** [INFO-526-S24/project-final-DataDazzlers#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Sachin Pandurang Patil - @sachin3115
- Valerie Okine - @valerie-okine
- Arun Kondinya Parasa - @ArunKoundinya
- Surajit Pal - @sura789
- Christian Ortmann - @christian-ortmann
- Peter Yeh - @Peter-Yeh-coder

- Describe the goal of the project.

The project aims to analyze the Tucson accident crash dataset to uncover patterns and factors contributing to road accidents, focusing on high-risk areas and times, while proposing data-driven recommendations for enhancing road safety measures in Tucson, ultimately contributing to reducing traffic-related injuries and fatalities.

- Describe the data used or collected.
  This is the source of the dataset. { [Link](https://gisdata.tucsonaz.gov/datasets/tucson-police-collisions/explore) }
  Collisions documented by the Tucson Police Department, 2017 - Present.
  Total number of data records - 35,598 and total number of columns - 51.
     Looks like important columns could be: Collision date, Offense Desc, Injury Sevirity, Collision Neighbourhood, Accident Location & Fatalities to our comprehension.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
   The teams end goal seems to utilize advanced data analysis and visualization techniques to enhance road safety measures in Tucson, ultimately reducing traffic-related injuries and fatalities. 
  Approach seems to be in this fashion:
     1) Data preparation and analysis, cleaning and preprocessing the Tucson accident crash dataset, focusing on temporal trends, spatial distribution, and accident severity. 
     2) Then, team will develop an interactive dashboard using R Shiny, featuring filters for user exploration, Leaflet for spatial data display, and ggplot2/Plotly for dynamic visualizations. 

- Is there anything that is unclear from the proposal?
   Since, there are 51 columns it should be very clear what the dashboard would answer, which is clearly missing in the proposal.  There is just an over-arching objective also the research questions are missing.

- Provide constructive feedback on how the team might be able to improve their project.
   What is good:
     -  Objective is very good.
     - Project Plan is good.
     - Expected outcome is intriguing. 
   
   What needs to be improved:
      - Key attributes out of 51 needs to be mentioned; atleast few of them that seems to be insightful could have been mentioned.
      - Research questions should be defined. Because for a business user, what questions will answer by viewing the dashboard.
      - Detailing about the graphs and their approach would help to give more nuanced feedback.
      - In Data Analysis, team has mentioned about the weather impact. but there is no related data available in the document.
   
  
- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

   We are interested specially about the location and time of the accidents and its related insights. 

- Provide constructive feedback on any issues with file and/or code organization.

      - Team member names are missing.
      - Timeline dates needs to be changed.
      - Loading of libraries should have been at the start of the document.

- (Optional) Any further comments or feedback? 
      All the best!

**Comment by sdmitrovic** [comment]
Thank you for this feedback. We have now defined two research questions, which variables we want to use to answer these questions, and which plots we want to create based on these analysis goals. We have also removed the mention of weather impact since this dataset does not include that variable. Finally, the team member names and timeline to completion have been added as well as making sure to load the libraries at the beginning of the document.
