### ISSUE TITLE
Proposal peer review from Graphical Geniuses

### ISSUE THREAD

**Issue by Praveen-Kumar-Pappala** [INFO-526-S24/project-final-DataDazzlers#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Tushar Kant Singh - @[ustusharkant]
- Pradnya Raut - @[PradnyaR24]
- Praveen Kumar Pappala - @[Praveen-Kumar-Pappala]
- Mobolaji Adewale - @[Bolajiadewal3]
- Usama Ahmed @[usamaahmedsh]
- Narasimha Vardhan Rachaputi @[nvrachaputi]

- Describe the goal of the project.
The goal of the project is to develop a dynamic and user-friendly tool that offers detailed insights into the frequency, severity, and causes of traffic accidents across different times and locations in Tucson.

- Describe the data used or collected.
 This Data-set is taken from the [GIS Data from the City of Tucson](https://gisdata.tucsonaz.gov/datasets/tucson-police-collisions/explore). The data description however is missing and not explicitly mentioned in the proposal.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
The team is utilizing R Shiny for the creation of an interactive dashboard, allowing users to filter and explore the data based on specific criteria (e.g., time period, accident severity). Implementing Leaflet for interactive maps to display spatial data and identify accident hotspots within Tucson. Using ggplot2 and Plotly for creating dynamic and static visualizations that can be adjusted according to user input.

- Is there anything that is unclear from the proposal?
Firstly, the dataset has not been described. Only the names of the variables have been mentioned, many of which are difficult to understand without description. Also the time period of the dataset is not mentioned.  And, the team could have been more specific with the variables they would be using for each of their mentioned analyses.

- Provide constructive feedback on how the team might be able to improve their project.
Displaying the head of their dataset would have given us a better insight. Also, being more specific about the data and information and the types of plots they would include in their analysis would give us a better idea. And mentioning, or in-fact, taking a dataset with a recent and long enough time period would give more accurate and meaningful trends.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The idea of displaying the traffic collision statistics of Tucson on interactive maps is an amazing idea. And allowing the user to interact with user friendly features, filters to highlight hotspots is definitely interesting. 

- Provide constructive feedback on any issues with file and/or code organization.
Everything looks good, just some typing errors to be fixed like "form", "colummns" in the second line of dataset section.

- (Optional) Any further comments or feedback?

**Comment by sdmitrovic** [comment]
Thank you for this feedback. We have now added a data description, better descriptions of the variables, and a specific plan of action that states our analysis questions and which variables/plots we want to use to answer these questions. We have also proofread the proposal and fixed any typos.
