### ISSUE TITLE
Presentation peer review-RoboCops

### ISSUE THREAD

**Issue by Peter-Yeh-coder** [INFO-526-S24/project-final-DataDazzlers#4]
The following is the peer review of the Presentation proposal by RoboCops. The team members that participated in this review are 

-Sachin Pandurang Patil - @sachinpatil3115
-Valerie Okine - @valerie-okine
-Arun Kondinya Parasa - @ArunKoundinya
-Surajit Pal - @sura789
-Christian Ortmann - @christian-ortmann
-Peter Yeh - @Peter-Yeh-coder

- Content: Is the research question well designed and is the data being used relevant to the research question?

The primary goal of the project is to develop a user-friendly, visualization tool that provides detailed insights into the frequency, severity, and causes of traffic accidents in Tucson.

The group uses GIS Data from the City of Tucson, which contains publicly-available records of vehicle collisions from the Tucson Police Department covering the period from March 2022 to the present.

The first question: Does day of the week and/or time of day affect severity and the number of accidents?
Data used:
Collision-date (date of collision in YMD format)
TimeOccu (time at which accident occurred)
MonthAccu (month in which accident occurred)
Day (day of week in which accident occurred)

The second question: What is the relationship between the type of violation and if the accident resulted in injury or fatality?
Data used:
Fatal Collision (if collision resulted in fatality, yes/no)
Total Fatalities (number of fatalities due to accidents)
Injury Severity (how serious the injury caused by accident was)
Violation/Operator Variables (intersection, speeding, impairment, and distracted)

The research is well designed for the topic and the data used is appropriate.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

The team used appropriate visualizations.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Limitations was not discussed. Yes a lot of time and effort was clearly spent to make a dashboard.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

For the plots, the text is too small to read.

Line plot: has no title. The plot is too busy. The presentation wanted to focus on 2019, but the plot did not highlight it specifically.

Line plot 2: axis labels is inconsistent (24 instead of 12:00 am). Also, is the 24 meant to be there since the tick does not match the values of the 12:00 am.

Heat map: there is no title and no axis labels, making the axis values unclear. Legend title is also absent.

Bar plot: axis title is inconsistent casing compared to previous plots.

Piechart plots: Ordering of the plots does not seem to have an ordering (ie left -> right high to low percent)

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

They presented very well and everyone had meaningful things to say. It does feel like they were reading off the slides though at times. Additionally, could have walked just walked through the dashboard instead of making the presentation since that was focus of the project.

**Comment by VidhyananthSivashanmugam** [comment]
We have made the necessary adjustments as mentioned
