### ISSUE TITLE
Code peer review from Graphical Geniuses

### ISSUE THREAD

**Issue by Praveen-Kumar-Pappala** [INFO-526-S24/project-final-DataDazzlers#5]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

Tushar Kant Singh - @[ustusharkant]

Pradnya Raut - @[PradnyaR24]

Praveen Kumar Pappala - @[Praveen-Kumar-Pappala]

Mobolaji Adewale - @[Bolajiadewal3]

Usama Ahmed @[usamaahmedsh]

Narasimha Vardhan Rachaputi @[nvrachaputi]

---

#### 1. Purpose of Code
- [x] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [x] Code is clean, readable, and well-organized
- [ ] Adequate comments explaining complex or tricky code sections
- [x] Variables, methods, and classes have meaningful names
- [x] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 4. Best Practices

- [x] No hardcoded values; constants used appropriately
- [x] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [x] Code avoids repetition and promotes reusability

---

#### 5. Additional Comments

- Lines 109-118. They could’ve used grepl instead of str_detect which is much more slower. They could have broken down the code in chunks.

---

#### 6. Recommendation

- [x] Approved - ready to be merged
- [ ] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by VidhyananthSivashanmugam** [comment]
The readme file and code documentation have been updated.
