### ISSUE TITLE
Code peer review from Robo Cops

### ISSUE THREAD

**Issue by ArunKoundinya** [INFO-526-S24/project-final-DataDazzlers#6]
The following is the peer review of the project code by [name of team completing peer review]. The team members that participated in this review are 

-Sachin Pandurang Patil - @sachinpatil3115
-Valerie Okine - @valerie-okine
-Arun Kondinya Parasa - @ArunKoundinya
-Surajit Pal - @sura789
-Christian Ortmann - @christian-ortmann
-Peter Yeh - @Peter-Yeh-coder

#### 1. Purpose of Code
- [ X] Clearly defined and understood
- [ X] Ambiguous or unclear

The code is meticulously detailed, but it can be unclear for a new reader because it lacks comments that explain its purpose. Comments are essential for helping readers understand the code's functionality and facilitating easier visualisation of its processes. 

#### 2. Code Quality

- [ X] Code is clean, readable, and well-organized
- [ X] Adequate comments explaining complex or tricky code sections
- [ X] Variables, methods, and classes have meaningful names
- [ X] Consistent code style (indentation, naming conventions, etc.)

Team has checked all the things 

The code maintains consistency in style across files by adhering to high standards for annotation with Highcharts, resulting in a visually appealing presentation. It's clean and well-organized, but as previously mentioned, incorporating additional comments would improve comprehension.

Furthermore, the meaningful variable names set a good example that we aim to emulate in our own coding practices.

---

#### 3. Documentation

- [ ] Code documentation (e.g., comments) is sufficient
- [ ] Readme or other documentation updated if necessary

The documentation of Readme needs to be updated.

#### 4. Best Practices

- [ ] No hardcoded values; constants used appropriately
- [ X] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [X ] Code avoids repetition and promotes reusability

The team has adhered to best coding practices by:
- Ensuring proper alignment of the code for improved readability.
- Employing correct alignment with dplyr pipes in conjunction with ggplots, enhancing clarity and consistency.

- However, as previously noted, including additional comments would further enhance understanding and maintain the code's accessibility.

#### 5. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

The code is meticulously detailed, but it can be unclear for a new reader because it lacks comments that explain its purpose. Comments are essential for helping readers understand the code's functionality and facilitating easier visualisation of its processes. 

#### 6. Recommendation

- [ ] Approved - ready to be merged
- [ X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

Code is approved. Comments can be incorporated.

**Comment by VidhyananthSivashanmugam** [comment]
The readme file and code documentation have been updated.
