### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by PradnyaR24** [INFO-526-S24/project-final-DataDazzlers#7]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

- Pradnya Raut - @[Pradnyar24]
- [Narasimha Rachaputi] - @[nvrachaputi]
- [Usama Ahmed] - @[usamaahmedsh]
- Tushar Kant Singh - @[ustusharkant]
- Praveen Kumar - @[praveen-kumar-pappala]
- Mobolaji Adewale - @[bolajiadewal3]
- ...

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes, the data was relevant to the presentation given.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
Yes, The bar plots and the line graphs in the presentation and the dashboard very visually appealing and made us to understand the data and the analysis clearly. 

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, it was a thoughtful project with relevant data 
limitations for the project are not mentioned 
but it is seen that considerable time and effort went into the planning and implementation of the project
The dashboard was interactive we really liked how it came out 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
The slides were well organized and most importantly they were short and sweet instead of using lengthy paragraphs which made the slides interesting and focus more on the presentation.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
The team presented very well and every part of the slide was explained clearly by every teammate. However, they missed on a lot of reasoning/interpretation. For example, in the collision (first plot), there was a clear dip for all collision types. They did not give any reason for why that dip occured.

**Comment by VidhyananthSivashanmugam** [comment]
We have added the ones that are required  as mentioned and made the necessary adjustments.
